### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by sadikkuzu** [VaasuDevanS/cowsay-python#17]
```
DEPRECATION:
Python 3.5 reached the end of its life on September 13th, 2020.
Please upgrade your Python as Python 3.5 is no longer maintained.
```

https://github.com/VaasuDevanS/cowsay-python/blob/86dc86e713e0654c31e37556853140723527fbcc/setup.py#L5

https://github.com/VaasuDevanS/cowsay-python/blob/2c2c301b1a7ffa91b92273503fd673d6a9c8a50f/.github/workflows/cowsay.yaml#L11

**Comment by gurashish1singh** [comment]
I would like to raise a PR for this, if no-one else is planning to.
