### ISSUE TITLE
Include methods that output cowsay as a string return value

### ISSUE THREAD

**Issue by nafiz1001** [VaasuDevanS/cowsay-python#7]
I believe this project would benefit from providing some means of outputing cowsay as a string return value. For example, in my fork, `cowsay.cow` would return a string instead of printing to the console.

My fork: 24352a73e3b81c085ebd9d834b258e463160b88a

The reason I did that is so my discord bot can send cowsays in chats.

**Comment by VaasuDevanS** [comment]
Added the function that exactly does the same. Update the cowsay package to the latest version (v4.0) 
Click [here](https://github.com/VaasuDevanS/cowsay-python/blob/master/CHANGELOG.md) for the version changes
`cowsay.get_output_string('trex', 'Hello (extinct) World')` will return the cowsay output as a string.
